
test_suite(
    name = "AllTests",
    tests = [
        "//submodules/TgVoipWebrtc:TgCallsTests",
        # MARK: NAGRAM
        "//Tests/NagramSessionMigrationTests:NagramSessionMigrationTests",
    ],
    visibility = [
        "//visibility:public",
    ],
)